"""Thin verl runtime integration bridges."""

from verl_gr.integrations.verl.rl_runtime import RLRuntimeConfig, RuntimeTrainerHandle, VerlRLRuntime
from verl_gr.integrations.verl.ray_trainer import RayPPOTrainerRuntime
from verl_gr.integrations.verl.openonerec_bridge import (
    get_actor_rollout_ref_worker,
    get_async_actor_rollout_ref_worker,
    get_compute_position_id_with_mask,
    get_copy_to_local,
    get_critic_worker,
    get_data_proto_cls,
    get_device_name,
    get_fsdp_reward_model_worker,
    get_fsdp_vllm_sharding_manager,
    get_log_gpu_memory_usage,
    get_megatron_ray_worker_group,
    get_megatron_reward_model_worker,
    get_megatron_worker_symbols,
    get_ppo_runtime_symbols,
    get_process_image_video,
    get_qwen2_vl_rope_index,
    get_ray_worker_group,
    get_torch_functional_module,
    get_vllm_rollout_spmd_symbols,
)
from verl_gr.integrations.verl.worker_factory import (
    WorkerFactoryConfig,
    WorkerRole,
    WorkerRouting,
    build_worker_routing,
)

__all__ = [
    "RLRuntimeConfig",
    "RayPPOTrainerRuntime",
    "RuntimeTrainerHandle",
    "VerlRLRuntime",
    "get_actor_rollout_ref_worker",
    "get_async_actor_rollout_ref_worker",
    "get_compute_position_id_with_mask",
    "get_copy_to_local",
    "get_critic_worker",
    "get_data_proto_cls",
    "get_device_name",
    "get_fsdp_reward_model_worker",
    "get_fsdp_vllm_sharding_manager",
    "get_log_gpu_memory_usage",
    "get_megatron_ray_worker_group",
    "get_megatron_reward_model_worker",
    "get_megatron_worker_symbols",
    "get_ppo_runtime_symbols",
    "get_process_image_video",
    "get_qwen2_vl_rope_index",
    "get_ray_worker_group",
    "get_torch_functional_module",
    "get_vllm_rollout_spmd_symbols",
    "WorkerFactoryConfig",
    "WorkerRole",
    "WorkerRouting",
    "build_worker_routing",
]
