defaults:
  - hf_model
  - _self_

# verl's activation offload implementation only supports FSDP/FSDP2.
enable_activation_offload: false
enable_gradient_checkpointing: true
use_remove_padding: true
use_fused_kernels: false
external_lib: verl_gr.workers.engine.ddp

fused_kernel_options:
  impl_backend: torch
