_target_: verl_gr.workers.config.ddp_engine.DDPEngineConfig
param_offload: false
optimizer_offload: false
grad_offload: false
forward_only: false
strategy: ddp
dtype: bfloat16
use_dynamic_bsz: true
max_token_len_per_gpu: null
micro_batch_size_per_gpu: null
infer_max_token_len_per_gpu: null
infer_micro_batch_size_per_gpu: null
use_fused_kernels: false
use_remove_padding: true
seed: 42
full_determinism: false
router_replay:
  _target_: verl.workers.config.EngineRouterReplayConfig
  mode: disabled
  record_file: null
  replay_file: null
ddp_find_unused_parameters: false
model_dtype: bf16
entropy_from_logits_with_chunking: false
use_torch_compile: true
entropy_checkpointing: false
qat:
  _target_: verl.workers.config.QATEngineConfig
  enable: false
  mode: w4a16
  group_size: 16
  ignore_patterns:
    - lm_head
    - embed_tokens
    - re:.*mlp.gate$
  activation_observer: static_minmax
  quantization_config_path: null
