defaults:
  - ../engine@engine_config: ddp
  - ref
  - _self_

_target_: verl_gr.workers.config.ddp_engine.DDPActorConfig
strategy: ${actor_rollout_ref.actor.strategy}
entropy_from_logits_with_chunking: false
entropy_checkpointing: false

engine_config:
  forward_only: true
